import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import { Container, Row } from "react-bootstrap";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Portfolio: Madhav Saraf",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
		<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
			<div className="App d-flex flex-column min-vh-100">
				{children}
			</div>
		</body>
    </html>
  );
}
